"""Centralized CSS selectors for Wyylde platform.

All CSS selectors used in wyylde.py and bot_engine.py are defined here
as constants. This makes it easy to update selectors when the site changes
without hunting through business logic code.

Reference: docs/wyylde_selectors.md (auto-generated by explorer)
"""

# ─── Navigation URLs ───
LOGIN_URL = "https://app.wyylde.com/fr-fr"
SEARCH_URL = "https://app.wyylde.com/fr-fr/search/user"
MESSAGES_URL = "https://app.wyylde.com/fr-fr/messages"
MAILBOX_URL = "https://app.wyylde.com/fr-fr/mailbox/inbox"

# ─── Chat sidebar (online profiles on dashboard) ───
CHAT_PROFILE_BUTTON = 'button[class*="bg-neutral-lowest"][class*="cursor-pointer"]'

# ─── Member links ───
MEMBER_LINK = 'a[href*="/member/"]'

# ─── Profile page ───
PROFILE_NAME = 'button.max-w-full.font-poppins'
FOLLOW_ICON = 'svg[data-icon="user-plus"]'
CRUSH_ICON = 'svg[data-icon="wyylde-crush"]'
LUI_ECRIRE_ICON = 'svg[data-icon="paper-plane"]'

# ─── Send button ───
SEND_ICON = 'svg[data-icon="paper-plane-top"]'

# ─── Editor (TipTap/ProseMirror) ───
TIPTAP_EDITOR = 'div.tiptap.ProseMirror[contenteditable="true"]'
CONTENTEDITABLE_FALLBACK = 'div[contenteditable="true"]'

# ─── Mailbox ───
INBOX_CONV_LINK = 'a[href*="/mailbox/inbox/"]'
MAILBOX_LINK = 'a[href*="/mailbox/"]'
INBOX_TAB = '#inbox'
SENT_TAB = '#sent'
ALL_TAB = 'button[name="all"]'

# ─── Search page ───
SEARCH_SUBMIT = 'input[type="submit"]'

# ─── Profile navigation arrows ───
NEXT_PROFILE_ICON = 'svg[data-icon="chevron-right"]'

# ─── Popup dismiss ───
MODAL_CLOSE = '[class*="modal"] button[class*="close"]'
DISMISS_BUTTON = 'button[class*="dismiss"]'
COOKIE_BUTTON = '[class*="cookie"] button'

# ─── Minimum X thresholds for element filtering ───
# Used in JS evaluate calls to distinguish main content from sidebar
MAIN_CONTENT_MIN_X = 300
CHAT_SIDEBAR_MIN_X = 1020
CHAT_SIDEBAR_MAX_X = 1150
MEMBER_LINK_MIN_X = 500
