"""Centralized selectors for Tinder Web.

Strategy: prefer stable attributes (aria-label, href patterns) over hashed CSS
classes. Tinder's React components ship with `Typs__StyledTyp-sc-XXXX` style
hashed class names that rotate per deploy. Run `POST /api/explore/tinder` after
any DOM drift and regenerate this file from `docs/tinder_selectors.md`.

Reference: docs/tinder_selectors.md (to be generated by explorer)
"""

# --- Navigation URLs ---
LOGIN_URL = "https://tinder.com"
RECS_URL = "https://tinder.com/app/recs"
MATCHES_URL = "https://tinder.com/app/matches"
MESSAGES_URL = "https://tinder.com/app/messages"
PROFILE_URL = "https://tinder.com/app/profile"

# --- Swipe buttons (aria-label is stable across deploys) ---
LIKE_BUTTON = 'button[aria-label*="Like"]:not([aria-label*="Super"])'
NOPE_BUTTON = 'button[aria-label*="Nope"], button[aria-label*="Pass"]'
SUPER_LIKE_BUTTON = 'button[aria-label*="Super"]'

# --- Keyboard fallback keys (Tinder Web built-ins) ---
KEY_LIKE = "ArrowRight"
KEY_NOPE = "ArrowLeft"
KEY_SUPER_LIKE = "ArrowUp"

# --- Profile card (current recs view) ---
# These often use hashed classes; prefer data-testid or itemprop when present.
PROFILE_NAME_FALLBACKS = [
    '[itemprop="name"]',
    'h1[class*="name"]',
    'span[class*="name"]',
    '[class*="Typs(display-1-strong)"]',
]
PROFILE_AGE_FALLBACKS = [
    '[itemprop="age"]',
    'span[class*="age"]',
    '[class*="Typs(display-2-regular)"]',
]
PROFILE_BIO_FALLBACKS = [
    '[class*="BreakWord"]',
    '[class*="bio"]',
    'div[class*="userBio"]',
]
PROFILE_PASSIONS_FALLBACKS = [
    '[class*="passion"]',
    '[class*="pill"]',
    '[class*="interest"]',
]
PROFILE_DISTANCE_FALLBACKS = [
    '[class*="distance"]',
    'div:has-text("km away"), div:has-text("miles away")',
]

# --- Match list ---
MATCH_LINK = 'a[href^="/app/messages/"]'
MATCH_NAME_FALLBACKS = ['[class*="name"]', 'span']

# --- Chat / message input ---
MESSAGE_INPUT_FALLBACKS = [
    'textarea[placeholder*="Type a message"]',
    'textarea[placeholder*="Message"]',
    'div[contenteditable="true"]',
    'textarea',
]
SEND_BUTTON_FALLBACKS = [
    'button[type="submit"]',
    'button[class*="send"]',
    'button[aria-label*="Send"]',
]

# --- Popups to dismiss ---
POPUP_DISMISS_FALLBACKS = [
    '[class*="matchAnimation"] button',
    'button[title*="Back"]',
    'button[aria-label*="Back"]',
    '[class*="modal"] button[class*="close"]',
    'button[aria-label*="Close"]',
    'button[aria-label*="Dismiss"]',
]

# --- Out-of-likes / rate-limit signals ---
OUT_OF_LIKES_TEXT = "You've seen everyone"
RATE_LIMIT_TEXT_FALLBACKS = [
    "You've run out of likes",
    "Come back later",
]
